name: Pipeline CI/CD - Projeto ESG
on:
  push:
    branches: [ "main" ]

jobs:
  build_e_teste:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v3

      - name: 2. Configurar o Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 3. Buildar com Maven
        run: mvn clean install

  publicar_no_dockerhub:
    needs: build_e_teste
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v3

      - name: 2. Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 3. Build e Push da Imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pablocabugueira/inclusaoapp:latest
  deploy:
    needs: publicar_no_dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Deploy em Staging
        run: |
          echo "Simulando deploy para o ambiente de Staging..."
          echo "Imagem seu-usuario-dockerhub/seu-repo:latest enviada."
          echo "Deploy de Staging concluído com sucesso!"

      - name: Deploy em Produção
        run: |
          echo "Simulando deploy para o ambiente de Produção..."
          echo "Deploy de Produção concluído com sucesso!"