-- Criação da tabela COLABORADOR
CREATE TABLE colaborador (
                             id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             nome VARCHAR2(100) NOT NULL,
                             genero VARCHAR2(50) NOT NULL,
                             etnia VARCHAR2(50) NOT NULL,
                             pcd NUMBER(1) NOT NULL, -- Booleano (0 ou 1)
                             departamento VARCHAR2(100) NOT NULL,
                             data_admissao DATE NOT NULL
);

-- Criação da tabela TREINAMENTO
CREATE TABLE treinamento (
                             id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             titulo VARCHAR2(150),
                             descricao VARCHAR2(500),
                             data DATE,
                             colaborador_id NUMBER,
                             CONSTRAINT fk_treinamento_colaborador FOREIGN KEY (colaborador_id)
                                 REFERENCES colaborador(id) ON DELETE SET NULL
);

-- Índices (opcional, mas recomendado)
CREATE INDEX idx_colaborador_departamento ON colaborador(departamento);
CREATE INDEX idx_treinamento_colaborador ON treinamento(colaborador_id);
